### ISSUE TITLE
UI Behaviour on Updated

### ISSUE THREAD

**Issue by adaptive** [cloudflare/cloudflare-docs-engine#304] opened 2020-11-10 16:01 UTC
When refreshing I see this behaviour, both normal and incognito.

**user-agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

![2020-11-10 15 52 34](https://user-images.githubusercontent.com/17833/98698113-9994b800-236d-11eb-95c1-b080a7b156e3.gif)

**Comment by adamschwartz** [comment] 2020-11-10 17:05
Please describe the issue that you’re seeing in a series of steps. I see the scrollbar flickering in the animated GIF, but I’m not quite sure what it is you’re saying that’s happening. If it’s hard to describe in words, perhaps make and attach a longer video that also includes the browser chrome (lowecased "c") in it.

**Comment by adaptive** [comment] 2020-11-10 19:02
sorry. my mistake describing.
right of `Edit on GitHub`, the `Updated 16 hours ago` flickers between 15 and 16 hours ago

**Comment by adamschwartz** [comment] 2020-11-10 19:46
Ah, gotcha. Thanks so much! This is a dupe of https://github.com/cloudflare/cloudflare-docs-engine/issues/288 then.

**Closed** 2020-11-10 19:46 UTC
Labels: duplicate
